-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- TODO: manual review — unknown section 'wallpaper {' on line 1

-- TODO: manual review — unknown section 'wallpaper {' on line 7

-- TODO: manual review — top-level key 'splash = false' has no enclosing section
