-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- TODO: manual review — unknown section 'listener {' on line 7

-- TODO: manual review — unknown section 'listener {' on line 12
hl.config({
    general = {
        lock_cmd = "pidof hyprlock || hyprlock",
        before_sleep_cmd = "loginctl lock-session",
        after_sleep_cmd = "hyprctl dispatch dpms on",
    },
})

